# Generated by Django 5.1.7 on 2025-04-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
